### PR TITLE
add pipeline config download to main nav

### PR DESCRIPTION
**Pull request by jacobheric**
Currently downloads the grpc `GetAllResponse.pipelines` as pretty printed json...but we can download whatever here. 

Screenshot 2024-04-17 at 12 09 16 PM
Screenshot 2024-04-17 at 12 08 27 PM

### CODE REVIEW

**Comment by dselans** [comment]
Latest server in main now has a `external.GetConfig()` using protos v0.1.41 - you should be able to update this to use that.

Same thing - return pretty printed JSON.

**Comment by dselans** [comment]
Also, let's change the link to "Download Config" - the endpoint you'll be hitting returns everything - audiences, pipelines, notifications, wasm, audience mappings.

**Review by fritzstauff — APPROVED** [review]
LGTM!

**Comment by jacobheric** [comment]
requested changes made

**Pull request merged**
