### PR TITLE
feat: introduce new tests and structure in console

### PR DESCRIPTION
**Pull request by nmashchenko**
This PR introduces new testing structure (as mentioned in https://github.com/streamdal/streamdal/issues/513#issuecomment-2406472751) and provides additional unit tests to increase coverage.

### CODE REVIEW

**Comment by uzarubin** [comment]
Thanks for the pr! Glad to have you deliver. Make sure to run deno fmt or the build will break. :)

**Review by uzarubin — APPROVED** [review]

**Comment by nmashchenko** [comment]
Hey there! Not exactly sure why PR is failing as I only introduced tests, looking into it now

**Comment by uzarubin** [comment]
Need to rebase against the change #516

**Comment by nmashchenko** [comment]
Fixed all issues! This guy should be ready now

**Pull request merged**
